# Generated by Django 3.0 on 2019-12-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191230_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_activation',
            field=models.BooleanField(default=False),
        ),
    ]
