# Generated by Django 3.1.5 on 2021-01-15 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('Desirable', 'Marked Desirable'), ('Unesirable', 'Marked Undesirable'), ('Commented', 'Commented'), ('Posted item', 'Posted Item'), ('Updated item', 'Updated Item'), ('Deleted item', 'Deleted item'), ('Registered account', 'Registered account'), ('Activated account', 'Activated account'), ('Updated account', 'Updated account'), ('Viewed item', 'Viewed item'), ('Browsed category', 'Browsed category')], max_length=250)),
                ('target_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('date_created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('target_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_obj', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ('-date_created',),
            },
        ),
    ]
