# Generated by Django 3.0.4 on 2020-03-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='target_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
