# Generated by Django 3.0.4 on 2020-03-08 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_activity_target_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='target_name',
        ),
    ]
