# Options file ('',''),
STATE_CHOICES = (
    ('Province 1', 'Province 1'),
    ('Province 2', 'Province 2'),
    ('Province 3', 'Province 3'),
    ('Province 4 (Gandaki)', 'Province 4 (Gandaki)'),
    ('Province 5', 'Province 5'),
    ('Province 6 (Karnali)', 'Province 6 (Karnali)'),
    ('Province 7 (Sudurpaschim)', 'Province 7 (Sudurpaschim)'),
)


CATEGORY_CHOICES = (
    ('Apparel&Accessories', 'Apparel and Accessories'),
    ('Automobiles', 'Automobiles'),
    ('Beauty&Health', 'Beauty and Health'),
    ('Books', 'Books'),
    ('Business&Industry', 'Business and Industry'),
    ('Computers&Peripherals', 'Computers and Peripherals'),
    ('Electronics', 'Electronics'),
    ('Events&Happenings', 'Events and Happenings'),
    ('Home,Furnishing&Appliances', 'Home, Furnishing and Appliances'),
    ('Jobs', 'Jobs'),
    ('Mobiles&Accessories', 'Mobiles and Accesories'),
    ('MusicInstruments', 'Music Instruments'),
    ('Pet&PetCare', 'Pet and Pet Care'),
    ('RealEstate', 'Real Estate'),
    ('Sports&Fitness', 'Sports and Fitness'),
    ('Services', 'Services'),
    ('Toys&VideoGames', 'Toys and Video Games'),
    ('Torism&Tours', 'Tourism and Tours'),
    ('Others', 'Others'),
)

SUB_CATEGORY_CHOICES = (
    # ('Apparel and Accessories', 'Apparel and Accessories'),
    ('ChildrenClothing', 'Children Clothing'),
    ('ChildrenAccessories', 'Children Accessories'),
    ('Bags&Luggage', 'Bags and Luggage'),
    ('Jwellery', 'Jwellery'),
    ('MensClothing', 'Mens Clothing'),
    ('MensAccessories', 'Mens Accessories'),
    ('MensShoes', 'Mens Shoes'),
    ('Sunglasses', 'Sunglasses'),
    ('Watches', 'Watches'),
    ('WomensClothing', 'Womens Clothing'),
    ('WomensAccessories', 'Womens Accessories'),
    ('WomensShoes', 'Womens Shoes'),
    ('Others', 'Others'),

    # ('Automobiles', 'Automobiles'),
    ('Cars', 'Cars'),
    ('Car:PartsandAccessories', 'Car: Parts and Accessories'),
    ('Motorcycle', 'Motorcycle'),
    ('Motorcycle:PartsandAccessories', 'Motorcycle: Parts and Accessories'),
    ('Bicycle', 'Bicycle'),
    ('Bicycle:PartsandAccessories', 'Bicycle: Parts and Accessories'),
    ('Other', 'Other'),

    # ('Beauty & Health','Beauty and Health'),
    ('BathToiletries', 'Bath Toiletries'),
    ('BodyCare', ' Body Care'),
    ('Cosmetics&Skin Care', 'Cosmetics & Skin Care'),
    ('ElectronicCigarette & Vape', 'Electronic Cigarette & Vape'),
    ('EyeCare', 'Eye Care'),
    ('FaceCare', 'Face Care'),
    ('Medical&HealthDevices', 'Medical & Health Devices'),
    ('MenGroomingTools', 'Men Grooming Tools'),
    ('Others', 'Others'),
    ('Perfumes & Fragrances', 'Perfumes & Fragrances'),
    ('Tattoo Equipment', 'Tattoo Equipment'),
    ('Women Grooming Tools', 'Women Grooming Tools'),

    # ('Books', 'Books'),
    ('Books', 'Books'),
    ('Others', 'Others'),

    #('Business & Industry','Business & Industry'),
    ('Raw', 'Raw'),
    ('Office', 'Office'),
    ('Machinery', 'Machinery'),
    ('Equipments', 'Equipments'),
    ('Dealership', 'Dealership'),
    ('Business', 'Business'),
    ('Wholesale', 'Wholesale'),
    ('Security', 'Security'),

    # ('Computers', 'Computers'),
    ('Storage&Memory', 'Storage & Memory'),
    ('Software', 'Software'),
    ('Printers&Scanners', 'Printers & Scanners'),
    ('Others', 'Others'),
    ('NetworkingEquipments', 'Networking Equipments'),
    ('Monitors', 'Monitors'),
    ('LaptopAccessories', 'Laptop Accessories'),
    ('Laptop', 'Laptop'),
    ('GraphicCards', 'Graphic Cards'),
    ('Games', 'Games'),
    ('DesktopAccessories', 'Desktop Accessories'),
    ('Desktop', 'Desktop'),

    # ('Electronics', 'Electronics'),
    ('HomeTheatre', 'Home Theatre'),
    ('Headphone&Earphone', 'Headphone & Earphone'),
    ('CameraAccessories', 'Camera Accessories'),
    ('Camcorder', 'Camcorder'),
    ('CinemaCamera', 'Cinema Camera'),
    ('Drones', 'Drones'),
    ('DIY&HobbyElectronics', 'DIY & Hobby Electronics'),
    ('DSLRCamera', 'DSLR Camera'),
    ('MirrorLessCamera', 'Mirror Less Camera'),
    ('DigitalCamera', 'Digital Camera'),
    ('Television', 'Television'),
    ('Projectors', 'Projectors'),
    ('Speakers', 'Speakers'),
    ('Others', 'Others'),
    ('MP3Players', 'MP3 Players'),

    # ('Events and Happenings','Events and Happenings')
    ('EventTickets', 'Event Tickets'),
    ('SportTickets', 'Sport Tickets'),
    ('MovieTickets', 'Movie Tickets'),
    ('ComicConTickets', 'Comic Con Tickets'),
    ('ConcertTickets', 'Concert Tickets'),


    # ('Furnitures', 'Furnitures'),
    ('Antique&Collectables', 'Antique & Collectables'),
    ('Paint&WallPapers', 'Paint & WallPapers'),
    ('Others', 'Others'),
    ('Linenes&Mattresses', 'Linenes & Mattresses'),
    ('Lighting&SolarElectricals', 'Lighting & Solar Electricals'),
    ('Kitchenware&Utensils', 'Kitchenware & Utensils'),
    ('KitchenAppliances', 'Kitchen Appliances'),
    ('Inverter&Generators', 'Inverter & Generators'),
    ('Decors&Interiors', 'Decors & Interiors'),
    ('HomeAppliances', 'Home Appliances'),
    ('Garden&Outdoor', 'Garden & Outdoor'),
    ('Food&Drinks', 'Food & Drinks'),
    ('ConstructionMaterials', 'Construction Materials'),
    ('Bath&Plumbing', 'Bath&Plumbing'),
    ('Art&Handicrafts', 'Art & Handicrafts'),

    # ('Jobs', 'Jobs'),
    ('Agriculte', 'Agriculture'),
    ('Theatre', 'Theatre'),
    ('Construction', 'Construction'),
    ('Business', 'Business'),
    ('Culinary&Cuisine', 'Culinary & Cuisine'),
    ('Labor', 'Labor'),
    ('Law', 'Law'),
    ('Marketing', 'Marketing'),
    ('IT', 'IT'),
    ('Service', 'Service'),
    ('Tourism', 'Tourism'),

    # ('Mobiles', 'Mobiles'),
    ('MobileHandsets', 'Mobile Handsets'),
    ('Tablets', 'Tablets'),
    ('Accesories', 'Accesories'),

    # ('Music Instruments', 'Music Instruments'),
    ('Music Instruments', 'Music Instruments'),

    # ('Pets', 'Pets'),
    ('Pets', 'Pets'),
    ('Pets care', 'Pets Care'),

    # ('Real Estate', 'Real Estate'),
    ('Flats', 'Flats'),
    ('Rooms', 'Rooms'),
    ('Land', 'Land'),
    ('House', 'House'),
    ('Others', 'Others'),

    # ('Sports and Fitness', 'Sports and Fitness'),
    ('SportsEquipments', 'Sports Equipments'),
    ('FitnessEquipments', 'Fitness Equipments'),

    # ('Services', 'Services'),
    ('Writing-Designing-Translating', 'Writing-Designing-Translating'),
    ('Visa&Migration', 'Visa & Migration'),
    ('OtherServices', 'Other Services'),
    ('Music-Video-Photography', 'Music-Video-Photography'),
    ('MoversCourier&Transport', 'Movers Courier & Transport'),
    ('HomeRepair&Maintainence', 'HomeRepair & Maintainence'),
    ('HomeConstruct&Design', 'Home Construct & Design'),
    ('Health,Fitness&Beauty', 'Health, Fitness & Beauty'),
    ('ForeignEducation', 'Foreign Education'),
    ('Financial&Legal', 'Financial & Legal'),
    ('EventPlanner&Caterers', 'Event Planner & Caterers'),
    ('ElectronicsRepair', 'Electronics Repair'),
    ('Courses-Education&Training', 'Courses - Education & Training'),
    ('Computer-Web&Design', 'Computer - Web &  Design'),
    ('Computer-Sales&Repair', 'Computer - Sales & Repair'),
    ('Coaching&Tutors', 'Coaching & Tutors'),
    ('Classes-Learning-Hobby-Music', 'Classes - Learning-Hobby-Music'),
    ('Advertising-Printing-Publication', 'Advertising-Printing-Publication'),

    # ('Toys&VideoGames', 'Toys and Video Games'),
    ('Toys', 'Toys'),
    ('VideoGames', 'Video Games'),
    ('Arcade', 'Arcade'),

    # ('Torism&Tours', 'Tourism and Tours')
    ('InternationalPackages', 'International Packages'),
    ('LocalPackages', 'Local Packages'),
)
