# Generated by Django 3.0 on 2020-01-07 13:14

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
