# Generated by Django 3.0.2 on 2020-02-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Apparel and Accessories', 'Apparel and Accessories'), ('Automobiles', 'Automobiles'), ('Beauty and Health', 'Beauty and Health'), ('Books', 'Books'), ('Business and Industry', 'Business and Industry'), ('Computers and Peripherals', 'Computers and Peripherals'), ('Electronics', 'Electronics'), ('Events and Happenings', 'Events and Happenings'), ('Home, Furnishing and Appliances', 'Home, Furnishing and Appliances'), ('Jobs', 'Jobs'), ('Mobiles and Accessories', 'Mobiles and Accesories'), ('Music Instruments', 'Music Instruments'), ('Pet and PetCare', 'Pet and Pet Care'), ('Real Estate', 'Real Estate'), ('Sports and Fitness', 'Sports and Fitness'), ('Services', 'Services'), ('Toys and Video Games', 'Toys and Video Games'), ('Torism and Tours', 'Tourism and Tours'), ('Others', 'Others')], max_length=100),
        ),
    ]
