# Generated by Django 3.0 on 2020-01-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(blank=True, choices=[('Brand-New', 'Brand New'), ('Used-Like-New', 'Used (Like New)'), ('Used-Worn-Out', 'Used (Worn Out)'), ('Defective', 'Defective')], max_length=100, null=True),
        ),
    ]
