# Generated by Django 3.0 on 2020-01-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20200102_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('realestate', 'Real Estate'), ('automobiles', 'Automobiles'), ('furnitures', 'Furniture'), ('jobs', 'Jobs'), ('computer', 'Computer'), ('mobiles', 'Mobiles'), ('books', 'Books'), ('electronics', 'Electronics'), ('cameras', 'Cameras'), ('music Instruments', 'Music Instruments'), ('pets', 'Pets'), ('sportsandfitness', 'Sports and Fitness'), ('services', 'Services'), ('clothing', 'Clothing')], max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
